theme = "blowfish"
baseURL = "https://kedzie-dev.github.io/"
defaultContentLanguage = "ko"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
summaryLength = 0

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]
