[[main]]
  name = "Cases"
  pageRef = "cases"
  weight = 10

[[main]]
  name = "Incident Labs"
  pageRef = "labs"
  weight = 15

[[main]]
  name = "Tech Map"
  pageRef = "tech-map"
  weight = 18

[[main]]
  name = "Notes"
  pageRef = "notes"
  weight = 20
