baseURL = 'https://johyobin.github.io/'
locale = 'ko-kr'
title = "johyobin's devops blog"
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
  env = 'production'
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true

[[menu.main]]
  identifier = 'portfolio'
  name = 'Portfolio'
  url = '/portfolio/'
  weight = 10

[[menu.main]]
  identifier = 'posts'
  name = 'Posts'
  url = '/posts/'
  weight = 20

[[menu.main]]
  identifier = 'search'
  name = 'Search'
  url = '/search/'
  weight = 30
